CREATE TABLE gender (
                        id_gender INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE person (
                        id_person INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        id_gender INTEGER NOT NULL,
                        full_name VARCHAR(50) NOT NULL,
                        birthdate DATE NOT NULL,
                        FOREIGN KEY (id_gender) REFERENCES gender(id_gender)
);
